### PR TITLE
Test travis with different hhvm versions

### PR DESCRIPTION
**Pull request by Ladsgroup**
It fails with segfault with the latest version. See https://github.com/facebook/hhvm/issues/7779

### CODE REVIEW

**Comment by Ladsgroup** [comment]
Didn't work

**Comment by mofarrell** [comment]
We suggest running HHVM on docker in travis.  If you are interested I should be able to point you at an example project.  The newest versions of HHVM don't support Ubuntu trusty, and travis has yet to add support for Ubuntu Xenial.  We get around this by using docker.
As far as the referenced issue, that should be fixed, and the packages and docker images should be updated within the week.

**Comment by Ladsgroup** [comment]
@mofarrell That'd be great.

**Comment by mofarrell** [comment]
This leaves out running with PHP, but [this project](https://github.com/facebook/xhp-lib) includes `.travis.yml` and `.travis.sh` that demonstrate testing on our docker images.

**Pull request closed without merging**
